app:
  env: dev
  port: 8888
  app_name: traffic-demo
  app_url: http://dev.example.com

MySQL:
  host: dev-mysql.internal
  port: 3306
  user: dev_user
  password: dev_pass_123
  db_name: traffic_dev
