SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE IF EXISTS `supply_chain_center`;
CREATE DATABASE `supply_chain_center` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `supply_chain_center`;

CREATE TABLE `sys_tenant` (
  `id` bigint unsigned NOT NULL,
  `tenant_code` varchar(64) NOT NULL,
  `tenant_name` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `contact_name` varchar(64) NOT NULL DEFAULT '',
  `contact_mobile` varchar(32) NOT NULL DEFAULT '',
  `expire_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_org` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `parent_id` bigint unsigned NOT NULL DEFAULT 0,
  `org_code` varchar(64) NOT NULL,
  `org_name` varchar(128) NOT NULL,
  `org_type` varchar(32) NOT NULL DEFAULT 'COMPANY',
  `org_level` int NOT NULL DEFAULT 1,
  `path` varchar(512) NOT NULL DEFAULT '',
  `leader_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_org_code` (`tenant_id`,`org_code`),
  KEY `idx_tenant_parent` (`tenant_id`,`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_dept` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `org_id` bigint unsigned NOT NULL,
  `parent_id` bigint unsigned NOT NULL DEFAULT 0,
  `dept_code` varchar(64) NOT NULL,
  `dept_name` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_dept_code` (`tenant_id`,`dept_code`),
  KEY `idx_org_parent` (`org_id`,`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_user` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `org_id` bigint unsigned NOT NULL,
  `dept_id` bigint unsigned NOT NULL DEFAULT 0,
  `username` varchar(64) NOT NULL,
  `real_name` varchar(64) NOT NULL,
  `mobile` varchar(32) NOT NULL DEFAULT '',
  `email` varchar(128) NOT NULL DEFAULT '',
  `password_hash` varchar(255) NOT NULL,
  `avatar_url` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `last_login_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_username` (`tenant_id`,`username`),
  UNIQUE KEY `uk_tenant_mobile` (`tenant_id`,`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_role` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `role_code` varchar(64) NOT NULL,
  `role_name` varchar(128) NOT NULL,
  `role_type` varchar(32) NOT NULL DEFAULT 'BUSINESS',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_role_code` (`tenant_id`,`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_user_role` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `role_id` bigint unsigned NOT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_role` (`tenant_id`,`user_id`,`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_menu` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `parent_id` bigint unsigned NOT NULL DEFAULT 0,
  `menu_code` varchar(64) NOT NULL,
  `menu_name` varchar(128) NOT NULL,
  `menu_type` varchar(32) NOT NULL DEFAULT 'MENU',
  `path` varchar(255) NOT NULL DEFAULT '',
  `component` varchar(255) NOT NULL DEFAULT '',
  `permission_code` varchar(128) NOT NULL DEFAULT '',
  `sort_no` int NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_menu_code` (`tenant_id`,`menu_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_role_menu` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `role_id` bigint unsigned NOT NULL,
  `menu_id` bigint unsigned NOT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_menu` (`tenant_id`,`role_id`,`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_data_permission` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `role_id` bigint unsigned NOT NULL,
  `data_scope` varchar(32) NOT NULL,
  `org_id` bigint unsigned NOT NULL DEFAULT 0,
  `warehouse_id` bigint unsigned NOT NULL DEFAULT 0,
  `ext_json` json DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_role_scope` (`tenant_id`,`role_id`,`data_scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_supplier` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `supplier_code` varchar(64) NOT NULL,
  `supplier_name` varchar(128) NOT NULL,
  `supplier_type` varchar(32) NOT NULL DEFAULT 'MANUFACTURER',
  `supplier_level` varchar(32) NOT NULL DEFAULT 'A',
  `contact_name` varchar(64) NOT NULL DEFAULT '',
  `contact_mobile` varchar(32) NOT NULL DEFAULT '',
  `contact_email` varchar(128) NOT NULL DEFAULT '',
  `country` varchar(64) NOT NULL DEFAULT '中国',
  `province` varchar(64) NOT NULL DEFAULT '',
  `city` varchar(64) NOT NULL DEFAULT '',
  `district` varchar(64) NOT NULL DEFAULT '',
  `address` varchar(255) NOT NULL DEFAULT '',
  `tax_no` varchar(64) NOT NULL DEFAULT '',
  `bank_name` varchar(128) NOT NULL DEFAULT '',
  `bank_account` varchar(64) NOT NULL DEFAULT '',
  `settlement_type` varchar(32) NOT NULL DEFAULT 'MONTHLY',
  `payment_term` varchar(64) NOT NULL DEFAULT '30D',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_supplier_code` (`tenant_id`,`supplier_code`),
  KEY `idx_tenant_supplier_name` (`tenant_id`,`supplier_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_supplier_contact` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `supplier_id` bigint unsigned NOT NULL,
  `contact_name` varchar(64) NOT NULL,
  `mobile` varchar(32) NOT NULL DEFAULT '',
  `email` varchar(128) NOT NULL DEFAULT '',
  `position` varchar(64) NOT NULL DEFAULT '',
  `is_default` tinyint NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_supplier_id` (`supplier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_customer` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `customer_code` varchar(64) NOT NULL,
  `customer_name` varchar(128) NOT NULL,
  `customer_type` varchar(32) NOT NULL DEFAULT 'DISTRIBUTOR',
  `customer_level` varchar(32) NOT NULL DEFAULT 'A',
  `contact_name` varchar(64) NOT NULL DEFAULT '',
  `contact_mobile` varchar(32) NOT NULL DEFAULT '',
  `contact_email` varchar(128) NOT NULL DEFAULT '',
  `country` varchar(64) NOT NULL DEFAULT '中国',
  `province` varchar(64) NOT NULL DEFAULT '',
  `city` varchar(64) NOT NULL DEFAULT '',
  `district` varchar(64) NOT NULL DEFAULT '',
  `address` varchar(255) NOT NULL DEFAULT '',
  `tax_no` varchar(64) NOT NULL DEFAULT '',
  `settlement_type` varchar(32) NOT NULL DEFAULT 'MONTHLY',
  `payment_term` varchar(64) NOT NULL DEFAULT '30D',
  `credit_limit` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_customer_code` (`tenant_id`,`customer_code`),
  KEY `idx_tenant_customer_name` (`tenant_id`,`customer_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_customer_contact` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `customer_id` bigint unsigned NOT NULL,
  `contact_name` varchar(64) NOT NULL,
  `mobile` varchar(32) NOT NULL DEFAULT '',
  `email` varchar(128) NOT NULL DEFAULT '',
  `position` varchar(64) NOT NULL DEFAULT '',
  `is_default` tinyint NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_customer_id` (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_brand` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `brand_code` varchar(64) NOT NULL,
  `brand_name` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_brand_code` (`tenant_id`,`brand_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_category` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `parent_id` bigint unsigned NOT NULL DEFAULT 0,
  `category_code` varchar(64) NOT NULL,
  `category_name` varchar(128) NOT NULL,
  `category_level` int NOT NULL DEFAULT 1,
  `path` varchar(512) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_category_code` (`tenant_id`,`category_code`),
  KEY `idx_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_unit` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `unit_code` varchar(64) NOT NULL,
  `unit_name` varchar(64) NOT NULL,
  `unit_type` varchar(32) NOT NULL DEFAULT 'QTY',
  `precision_digits` int NOT NULL DEFAULT 6,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_unit_code` (`tenant_id`,`unit_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_tax_rate` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `tax_code` varchar(64) NOT NULL,
  `tax_name` varchar(128) NOT NULL,
  `tax_rate` decimal(10,4) NOT NULL DEFAULT 0.0000,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_tax_code` (`tenant_id`,`tax_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_warehouse` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `org_id` bigint unsigned NOT NULL,
  `warehouse_code` varchar(64) NOT NULL,
  `warehouse_name` varchar(128) NOT NULL,
  `warehouse_type` varchar(32) NOT NULL DEFAULT 'CDC',
  `warehouse_level` varchar(32) NOT NULL DEFAULT 'L1',
  `country` varchar(64) NOT NULL DEFAULT '中国',
  `province` varchar(64) NOT NULL DEFAULT '',
  `city` varchar(64) NOT NULL DEFAULT '',
  `district` varchar(64) NOT NULL DEFAULT '',
  `address` varchar(255) NOT NULL DEFAULT '',
  `manager_id` bigint unsigned NOT NULL DEFAULT 0,
  `phone` varchar(32) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_warehouse_code` (`tenant_id`,`warehouse_code`),
  KEY `idx_org_id` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_warehouse_area` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `area_code` varchar(64) NOT NULL,
  `area_name` varchar(128) NOT NULL,
  `area_type` varchar(32) NOT NULL DEFAULT 'STORAGE',
  `temperature_type` varchar(32) NOT NULL DEFAULT 'NORMAL',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wh_area_code` (`warehouse_id`,`area_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mdm_location` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `area_id` bigint unsigned NOT NULL,
  `location_code` varchar(64) NOT NULL,
  `location_name` varchar(128) NOT NULL,
  `location_type` varchar(32) NOT NULL DEFAULT 'SHELF',
  `length` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `width` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `height` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `capacity_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `is_pickable` tinyint NOT NULL DEFAULT 1,
  `is_locked` tinyint NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wh_location_code` (`warehouse_id`,`location_code`),
  KEY `idx_area_id` (`area_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_spu` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `spu_code` varchar(64) NOT NULL,
  `spu_name` varchar(128) NOT NULL,
  `category_id` bigint unsigned NOT NULL,
  `brand_id` bigint unsigned NOT NULL,
  `product_type` varchar(32) NOT NULL DEFAULT 'NORMAL',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `attr_json` json DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_spu_code` (`tenant_id`,`spu_code`),
  KEY `idx_category_id` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_sku` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `spu_id` bigint unsigned NOT NULL,
  `sku_code` varchar(64) NOT NULL,
  `sku_name` varchar(128) NOT NULL,
  `barcode` varchar(64) NOT NULL,
  `spec_json` json DEFAULT NULL,
  `base_unit_id` bigint unsigned NOT NULL,
  `assist_unit_id` bigint unsigned NOT NULL DEFAULT 0,
  `unit_convert_rate` decimal(18,6) NOT NULL DEFAULT 1.000000,
  `weight` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `volume` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `length` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `width` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `height` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `cost_price` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `sale_price` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `tax_rate_id` bigint unsigned NOT NULL DEFAULT 0,
  `batch_required` tinyint NOT NULL DEFAULT 0,
  `serial_required` tinyint NOT NULL DEFAULT 0,
  `shelf_life_days` int NOT NULL DEFAULT 0,
  `enable_negative_stock` tinyint NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_sku_code` (`tenant_id`,`sku_code`),
  KEY `idx_barcode` (`barcode`),
  KEY `idx_spu_id` (`spu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_sku_barcode` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `barcode` varchar(64) NOT NULL,
  `barcode_type` varchar(32) NOT NULL DEFAULT 'EAN13',
  `is_primary` tinyint NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_barcode` (`tenant_id`,`barcode`),
  KEY `idx_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_sku_attr` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `attr_code` varchar(64) NOT NULL,
  `attr_name` varchar(128) NOT NULL,
  `attr_value` varchar(255) NOT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_price` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `price_type` varchar(32) NOT NULL,
  `org_id` bigint unsigned NOT NULL DEFAULT 0,
  `customer_id` bigint unsigned NOT NULL DEFAULT 0,
  `currency` varchar(16) NOT NULL DEFAULT 'CNY',
  `price` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `effective_from` datetime(3) NOT NULL,
  `effective_to` datetime(3) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_sku_price_type` (`tenant_id`,`sku_id`,`price_type`),
  KEY `idx_effective_time` (`effective_from`,`effective_to`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `purchase_requisition` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `req_no` varchar(64) NOT NULL,
  `org_id` bigint unsigned NOT NULL,
  `req_type` varchar(32) NOT NULL DEFAULT 'NORMAL',
  `req_status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `approve_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `required_date` date DEFAULT NULL,
  `applicant_id` bigint unsigned NOT NULL DEFAULT 0,
  `total_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_req_no` (`tenant_id`,`req_no`),
  KEY `idx_org_status` (`org_id`,`req_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `purchase_requisition_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `req_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `unit_id` bigint unsigned NOT NULL,
  `req_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `converted_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `estimated_price` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `estimated_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `required_date` date DEFAULT NULL,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_req_line` (`req_id`,`line_no`),
  KEY `idx_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `purchase_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `po_no` varchar(64) NOT NULL,
  `org_id` bigint unsigned NOT NULL,
  `supplier_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `source_type` varchar(32) NOT NULL DEFAULT '',
  `source_no` varchar(64) NOT NULL DEFAULT '',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY',
  `po_status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `approve_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `delivery_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `expected_arrival_date` date DEFAULT NULL,
  `total_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `discount_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `tax_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `payable_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_po_no` (`tenant_id`,`po_no`),
  KEY `idx_supplier_status` (`supplier_id`,`po_status`),
  KEY `idx_org_created` (`org_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `purchase_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `po_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `source_line_id` bigint unsigned NOT NULL DEFAULT 0,
  `sku_id` bigint unsigned NOT NULL,
  `unit_id` bigint unsigned NOT NULL,
  `order_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `received_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `returned_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `pending_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unit_price` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `discount_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `tax_rate` decimal(10,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `delivery_date` date DEFAULT NULL,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_po_line` (`po_id`,`line_no`),
  KEY `idx_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `purchase_receipt` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `receipt_no` varchar(64) NOT NULL,
  `po_id` bigint unsigned NOT NULL,
  `supplier_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `receipt_status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `qc_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `received_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_receipt_no` (`tenant_id`,`receipt_no`),
  KEY `idx_po_id` (`po_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `purchase_receipt_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `receipt_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `po_line_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `production_date` date DEFAULT NULL,
  `expire_date` date DEFAULT NULL,
  `received_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qualified_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `rejected_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unit_cost` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_receipt_line` (`receipt_id`,`line_no`),
  KEY `idx_po_line_id` (`po_line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `purchase_return_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `return_no` varchar(64) NOT NULL,
  `supplier_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `source_receipt_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `approve_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `total_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_purchase_return_no` (`tenant_id`,`return_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `purchase_return_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `return_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `source_receipt_line_id` bigint unsigned NOT NULL DEFAULT 0,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `return_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unit_price` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_return_line` (`return_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sales_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `so_no` varchar(64) NOT NULL,
  `org_id` bigint unsigned NOT NULL,
  `customer_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `channel_type` varchar(32) NOT NULL DEFAULT 'B2B',
  `source_order_no` varchar(64) NOT NULL DEFAULT '',
  `sales_type` varchar(32) NOT NULL DEFAULT 'NORMAL',
  `order_status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `approve_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `payment_status` varchar(32) NOT NULL DEFAULT 'UNPAID',
  `delivery_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY',
  `total_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `discount_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `tax_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `payable_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `order_time` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_so_no` (`tenant_id`,`so_no`),
  KEY `idx_source_order_no` (`tenant_id`,`source_order_no`),
  KEY `idx_customer_status` (`customer_id`,`order_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sales_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `so_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `unit_id` bigint unsigned NOT NULL,
  `order_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `allocated_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `shipped_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `returned_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `pending_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unit_price` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `discount_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `tax_rate` decimal(10,4) NOT NULL DEFAULT 0.0000,
  `tax_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_so_line` (`so_id`,`line_no`),
  KEY `idx_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sales_delivery_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `delivery_no` varchar(64) NOT NULL,
  `so_id` bigint unsigned NOT NULL,
  `customer_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `delivery_status` varchar(32) NOT NULL DEFAULT 'CREATED',
  `shipped_at` datetime(3) DEFAULT NULL,
  `carrier_id` bigint unsigned NOT NULL DEFAULT 0,
  `tracking_no` varchar(64) NOT NULL DEFAULT '',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_delivery_no` (`tenant_id`,`delivery_no`),
  KEY `idx_so_id` (`so_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sales_delivery_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `delivery_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `so_line_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `delivery_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `signed_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_delivery_line` (`delivery_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sales_return_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `return_no` varchar(64) NOT NULL,
  `customer_id` bigint unsigned NOT NULL,
  `source_so_id` bigint unsigned NOT NULL DEFAULT 0,
  `warehouse_id` bigint unsigned NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `approve_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `refund_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `refund_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_sales_return_no` (`tenant_id`,`return_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sales_return_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `return_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `source_so_line_id` bigint unsigned NOT NULL DEFAULT 0,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `return_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unit_price` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `refund_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_return_line` (`return_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_stock` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `org_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `location_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `stock_status` varchar(32) NOT NULL DEFAULT 'GOOD',
  `owner_type` varchar(32) NOT NULL DEFAULT 'SELF',
  `owner_id` bigint unsigned NOT NULL DEFAULT 0,
  `qty_on_hand` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qty_available` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qty_reserved` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qty_locked` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qty_in_transit` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qty_damaged` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `last_txn_time` datetime(3) DEFAULT NULL,
  `version` int NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stock_dim` (`tenant_id`,`org_id`,`warehouse_id`,`location_id`,`sku_id`,`batch_no`,`stock_status`,`owner_type`,`owner_id`),
  KEY `idx_sku_wh` (`tenant_id`,`sku_id`,`warehouse_id`),
  KEY `idx_wh_loc` (`warehouse_id`,`location_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_batch` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL,
  `production_date` date DEFAULT NULL,
  `expire_date` date DEFAULT NULL,
  `supplier_id` bigint unsigned NOT NULL DEFAULT 0,
  `receipt_no` varchar(64) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_dim` (`tenant_id`,`warehouse_id`,`sku_id`,`batch_no`),
  KEY `idx_expire_date` (`expire_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_serial_no` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `serial_no` varchar(64) NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `location_id` bigint unsigned NOT NULL,
  `stock_status` varchar(32) NOT NULL DEFAULT 'GOOD',
  `biz_status` varchar(32) NOT NULL DEFAULT 'IN_STOCK',
  `source_biz_no` varchar(64) NOT NULL DEFAULT '',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_serial_no` (`tenant_id`,`serial_no`),
  KEY `idx_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_txn` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `txn_no` varchar(64) NOT NULL,
  `biz_type` varchar(32) NOT NULL,
  `biz_no` varchar(64) NOT NULL,
  `biz_line_no` varchar(64) NOT NULL DEFAULT '',
  `direction` tinyint NOT NULL,
  `org_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `location_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `stock_status` varchar(32) NOT NULL DEFAULT 'GOOD',
  `before_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `change_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `after_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unit_cost` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `operator_id` bigint unsigned NOT NULL DEFAULT 0,
  `occurred_at` datetime(3) NOT NULL,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_txn_no` (`tenant_id`,`txn_no`),
  KEY `idx_biz_no` (`tenant_id`,`biz_type`,`biz_no`),
  KEY `idx_sku_wh_time` (`tenant_id`,`sku_id`,`warehouse_id`,`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_reservation` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `reservation_no` varchar(64) NOT NULL,
  `biz_type` varchar(32) NOT NULL,
  `biz_no` varchar(64) NOT NULL,
  `biz_line_no` varchar(64) NOT NULL DEFAULT '',
  `org_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `reserved_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `released_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `used_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `status` varchar(32) NOT NULL DEFAULT 'INIT',
  `expired_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_reservation_no` (`tenant_id`,`reservation_no`),
  KEY `idx_biz_no` (`tenant_id`,`biz_type`,`biz_no`),
  KEY `idx_expired_at` (`expired_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_lock` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `lock_no` varchar(64) NOT NULL,
  `biz_type` varchar(32) NOT NULL,
  `biz_no` varchar(64) NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `lock_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unlock_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `status` varchar(32) NOT NULL DEFAULT 'LOCKED',
  `expired_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_lock_no` (`tenant_id`,`lock_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_snapshot_daily` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `snapshot_date` date NOT NULL,
  `org_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `location_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `stock_status` varchar(32) NOT NULL DEFAULT 'GOOD',
  `qty_on_hand` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qty_available` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qty_reserved` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qty_locked` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `qty_in_transit` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_snapshot_dim` (`tenant_id`,`snapshot_date`,`warehouse_id`,`location_id`,`sku_id`,`batch_no`,`stock_status`),
  KEY `idx_snapshot_date` (`snapshot_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_count_task` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `count_no` varchar(64) NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `count_type` varchar(32) NOT NULL DEFAULT 'FULL',
  `scope_type` varchar(32) NOT NULL DEFAULT 'WAREHOUSE',
  `scope_json` json DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `approve_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `count_start_at` datetime(3) DEFAULT NULL,
  `count_end_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_count_no` (`tenant_id`,`count_no`),
  KEY `idx_wh_status` (`warehouse_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_count_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `count_task_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `location_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `system_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `counted_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `diff_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `adjust_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_count_line` (`count_task_id`,`line_no`),
  KEY `idx_sku_loc` (`sku_id`,`location_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_adjust_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `adjust_no` varchar(64) NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `adjust_type` varchar(32) NOT NULL DEFAULT 'PROFIT_LOSS',
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `approve_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `reason_code` varchar(64) NOT NULL DEFAULT '',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_adjust_no` (`tenant_id`,`adjust_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_adjust_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `adjust_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `location_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `before_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `adjust_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `after_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `unit_cost` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_adjust_line` (`adjust_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_inbound_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `inbound_no` varchar(64) NOT NULL,
  `biz_type` varchar(32) NOT NULL,
  `biz_no` varchar(64) NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `inbound_status` varchar(32) NOT NULL DEFAULT 'CREATED',
  `expected_at` datetime(3) DEFAULT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_inbound_no` (`tenant_id`,`inbound_no`),
  KEY `idx_biz_no` (`tenant_id`,`biz_type`,`biz_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_inbound_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `inbound_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `expected_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `received_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `putaway_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_inbound_line` (`inbound_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_putaway_task` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `task_no` varchar(64) NOT NULL,
  `inbound_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `task_status` varchar(32) NOT NULL DEFAULT 'CREATED',
  `assigned_to` bigint unsigned NOT NULL DEFAULT 0,
  `start_at` datetime(3) DEFAULT NULL,
  `finish_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_putaway_task_no` (`tenant_id`,`task_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_putaway_task_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `task_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `from_location_id` bigint unsigned NOT NULL,
  `to_location_id` bigint unsigned NOT NULL,
  `task_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `done_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_putaway_line` (`task_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_outbound_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `outbound_no` varchar(64) NOT NULL,
  `biz_type` varchar(32) NOT NULL,
  `biz_no` varchar(64) NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `wave_no` varchar(64) NOT NULL DEFAULT '',
  `outbound_status` varchar(32) NOT NULL DEFAULT 'CREATED',
  `completed_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_outbound_no` (`tenant_id`,`outbound_no`),
  KEY `idx_biz_no` (`tenant_id`,`biz_type`,`biz_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_outbound_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `outbound_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `required_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `allocated_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `picked_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `shipped_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_outbound_line` (`outbound_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_pick_task` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `task_no` varchar(64) NOT NULL,
  `outbound_id` bigint unsigned NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `pick_type` varchar(32) NOT NULL DEFAULT 'SINGLE',
  `task_status` varchar(32) NOT NULL DEFAULT 'CREATED',
  `assigned_to` bigint unsigned NOT NULL DEFAULT 0,
  `start_at` datetime(3) DEFAULT NULL,
  `finish_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_pick_task_no` (`tenant_id`,`task_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_pick_task_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `task_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `from_location_id` bigint unsigned NOT NULL,
  `pick_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `picked_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pick_task_line` (`task_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_wave` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `wave_no` varchar(64) NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `wave_type` varchar(32) NOT NULL DEFAULT 'NORMAL',
  `wave_status` varchar(32) NOT NULL DEFAULT 'CREATED',
  `release_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_wave_no` (`tenant_id`,`wave_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_wave_order_rel` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `wave_id` bigint unsigned NOT NULL,
  `outbound_id` bigint unsigned NOT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wave_outbound` (`wave_id`,`outbound_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_transfer_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `transfer_no` varchar(64) NOT NULL,
  `from_warehouse_id` bigint unsigned NOT NULL,
  `to_warehouse_id` bigint unsigned NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `approve_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `shipped_at` datetime(3) DEFAULT NULL,
  `received_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_transfer_no` (`tenant_id`,`transfer_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_transfer_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `transfer_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `transfer_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `shipped_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `received_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_transfer_line` (`transfer_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_move_order` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `move_no` varchar(64) NOT NULL,
  `warehouse_id` bigint unsigned NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `approve_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_move_no` (`tenant_id`,`move_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wms_move_order_line` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `move_id` bigint unsigned NOT NULL,
  `line_no` int NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `batch_no` varchar(64) NOT NULL DEFAULT '',
  `from_location_id` bigint unsigned NOT NULL,
  `to_location_id` bigint unsigned NOT NULL,
  `move_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `done_qty` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `line_status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_move_line` (`move_id`,`line_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `settlement_ap_bill` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `bill_no` varchar(64) NOT NULL,
  `supplier_id` bigint unsigned NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_no` varchar(64) NOT NULL,
  `bill_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `tax_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `paid_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `due_date` date DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_ap_bill_no` (`tenant_id`,`bill_no`),
  KEY `idx_supplier_status` (`supplier_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `settlement_ar_bill` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `bill_no` varchar(64) NOT NULL,
  `customer_id` bigint unsigned NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_no` varchar(64) NOT NULL,
  `bill_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `tax_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `received_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `status` varchar(32) NOT NULL DEFAULT 'OPEN',
  `due_date` date DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_ar_bill_no` (`tenant_id`,`bill_no`),
  KEY `idx_customer_status` (`customer_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `settlement_payment` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `payment_no` varchar(64) NOT NULL,
  `supplier_id` bigint unsigned NOT NULL,
  `pay_type` varchar(32) NOT NULL DEFAULT 'BANK',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY',
  `pay_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `pay_time` datetime(3) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'CREATED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_payment_no` (`tenant_id`,`payment_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `settlement_receipt` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `receipt_no` varchar(64) NOT NULL,
  `customer_id` bigint unsigned NOT NULL,
  `receipt_type` varchar(32) NOT NULL DEFAULT 'BANK',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY',
  `receipt_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `receipt_time` datetime(3) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'CREATED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_receipt_no` (`tenant_id`,`receipt_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `settlement_statement` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `statement_no` varchar(64) NOT NULL,
  `counterparty_type` varchar(32) NOT NULL,
  `counterparty_id` bigint unsigned NOT NULL,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `statement_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `confirmed_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_statement_no` (`tenant_id`,`statement_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `settlement_invoice` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `invoice_no` varchar(64) NOT NULL,
  `counterparty_type` varchar(32) NOT NULL,
  `counterparty_id` bigint unsigned NOT NULL,
  `invoice_type` varchar(32) NOT NULL DEFAULT 'VAT',
  `invoice_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `tax_amount` decimal(18,6) NOT NULL DEFAULT 0.000000,
  `invoice_date` date DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'CREATED',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_invoice_no` (`tenant_id`,`invoice_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `workflow_instance` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `instance_no` varchar(64) NOT NULL,
  `biz_type` varchar(32) NOT NULL,
  `biz_no` varchar(64) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'RUNNING',
  `current_node` varchar(64) NOT NULL DEFAULT '',
  `start_user_id` bigint unsigned NOT NULL,
  `start_at` datetime(3) DEFAULT NULL,
  `end_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_instance_no` (`tenant_id`,`instance_no`),
  KEY `idx_biz_no` (`tenant_id`,`biz_type`,`biz_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `workflow_task` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `instance_id` bigint unsigned NOT NULL,
  `node_code` varchar(64) NOT NULL,
  `task_name` varchar(128) NOT NULL,
  `assignee_id` bigint unsigned NOT NULL DEFAULT 0,
  `task_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `action` varchar(32) NOT NULL DEFAULT '',
  `action_at` datetime(3) DEFAULT NULL,
  `comment` varchar(255) NOT NULL DEFAULT '',
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_instance_id` (`instance_id`),
  KEY `idx_assignee_status` (`assignee_id`,`task_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `integration_idempotent` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `idempotent_key` varchar(128) NOT NULL,
  `biz_type` varchar(32) NOT NULL,
  `biz_no` varchar(64) NOT NULL,
  `request_hash` varchar(128) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL DEFAULT 'SUCCESS',
  `response_snapshot` json DEFAULT NULL,
  `expired_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_idempotent_key` (`tenant_id`,`idempotent_key`),
  KEY `idx_expired_at` (`expired_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `event_outbox` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `event_id` varchar(64) NOT NULL,
  `aggregate_type` varchar(64) NOT NULL,
  `aggregate_id` varchar(64) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `biz_no` varchar(64) NOT NULL DEFAULT '',
  `payload_json` json DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'NEW',
  `retry_count` int NOT NULL DEFAULT 0,
  `next_retry_at` datetime(3) DEFAULT NULL,
  `published_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_event_id` (`tenant_id`,`event_id`),
  KEY `idx_status_retry` (`status`,`next_retry_at`),
  KEY `idx_aggregate` (`aggregate_type`,`aggregate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `integration_api_log` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `biz_type` varchar(32) NOT NULL,
  `biz_no` varchar(64) NOT NULL,
  `interface_name` varchar(128) NOT NULL,
  `direction` varchar(16) NOT NULL,
  `request_uri` varchar(255) NOT NULL DEFAULT '',
  `request_body` json DEFAULT NULL,
  `response_body` json DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'SUCCESS',
  `error_msg` varchar(255) NOT NULL DEFAULT '',
  `request_at` datetime(3) DEFAULT NULL,
  `response_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_biz_no` (`tenant_id`,`biz_type`,`biz_no`),
  KEY `idx_interface_time` (`interface_name`,`request_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_audit_log` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `module` varchar(64) NOT NULL,
  `action` varchar(64) NOT NULL,
  `biz_type` varchar(32) NOT NULL,
  `biz_no` varchar(64) NOT NULL,
  `request_uri` varchar(255) NOT NULL DEFAULT '',
  `request_ip` varchar(64) NOT NULL DEFAULT '',
  `before_json` json DEFAULT NULL,
  `after_json` json DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_biz_no` (`tenant_id`,`biz_type`,`biz_no`),
  KEY `idx_user_time` (`user_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_login_log` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `username` varchar(64) NOT NULL,
  `login_ip` varchar(64) NOT NULL DEFAULT '',
  `login_result` varchar(32) NOT NULL DEFAULT 'SUCCESS',
  `user_agent` varchar(255) NOT NULL DEFAULT '',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_user_time` (`user_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_operate_log` (
  `id` bigint unsigned NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `module` varchar(64) NOT NULL,
  `operate_type` varchar(32) NOT NULL,
  `request_method` varchar(16) NOT NULL DEFAULT 'GET',
  `request_uri` varchar(255) NOT NULL DEFAULT '',
  `request_body` json DEFAULT NULL,
  `response_body` json DEFAULT NULL,
  `latency_ms` int NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'SUCCESS',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_module_time` (`module`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
